config/routes.rb
Rails.application.routes.draw do
  resources :product_licenses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product_license.rb
class ProductLicense < ApplicationRecord
  # ProductLicense consists of:
  # :license_key, :product_name, :purchasing_client, :client_seat, :service_tag
  # :created_at, :updated_at, :purchased
  validates :service_tag, length: { is: 7 }
  # TODO: Is it really needed to validate length? What about non-dell PCs?
  validates :purchasing_client, presence: true
  # TODO: What if the license hasn't been purchased yet? Need to rethink
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/product_licenses_controller.rb
class ProductLicensesController < ApplicationController
  before_action :set_product_license, only: [:show, :edit, :update, :destroy]

  # GET /product_licenses
  # GET /product_licenses.json
  def index
    @product_licenses = ProductLicense.all
  end

  # GET /product_licenses/1
  # GET /product_licenses/1.json
  def show
  end

  # GET /product_licenses/new
  def new
    @product_license = ProductLicense.new
  end

  # GET /product_licenses/1/edit
  def edit
  end

  # POST /product_licenses
  # POST /product_licenses.json
  def create
    @product_license = ProductLicense.new(product_license_params)

    respond_to do |format|
      if @product_license.save
        format.html { redirect_to @product_license, notice: 'Product license was successfully created.' }
        format.json { render :show, status: :created, location: @product_license }
      else
        format.html { render :new }
        format.json { render json: @product_license.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_licenses/1
  # PATCH/PUT /product_licenses/1.json
  def update
    respond_to do |format|
      if @product_license.update(product_license_params)
        format.html { redirect_to @product_license, notice: 'Product license was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_license }
      else
        format.html { render :edit }
        format.json { render json: @product_license.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_licenses/1
  # DELETE /product_licenses/1.json
  def destroy
    @product_license.destroy
    respond_to do |format|
      format.html {
        redirect_to product_licenses_url,
                    notice: 'Product license was successfully destroyed.'
      }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product_license
    @product_license = ProductLicense.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_license_params
    params.require(:product_license).permit(:license_key, :product_name,
                                            :purchasing_client, :client_seat,
                                            :service_tag, :purchased)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_licenses_helper.rb
module ProductLicensesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KeyTrack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/product_licenses/_form.html.erb
<%= form_with(model: product_license, local: true) do |form| %>
  <% if product_license.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_license.errors.count, "error") %> prohibited this product_license from being saved:</h2>

      <ul>
      <% product_license.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :license_key %>
    <%= form.text_field :license_key, id: :product_license_license_key %>
  </div>

  <div class="field">
    <%= form.label :product_name %>
    <%= form.text_field :product_name, id: :product_license_product_name %>
  </div>

  <div class="field">
    <%= form.label :purchasing_client %>
    <%= form.text_field :purchasing_client, id: :product_license_purchasing_client %>
  </div>

  <div class="field">
    <%= form.label :client_seat %>
    <%= form.text_field :client_seat, id: :product_license_client_seat %>
  </div>

  <div class="field">
    <%= form.label :service_tag %>
    <%= form.text_field :service_tag, id: :product_license_service_tag %>
  </div>

  <div class="field">
    <%= form.label :purchased %>
    <%= form.check_box :purchased %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/product_licenses/edit.html.erb
<h1>Editing Product License</h1>

<%= render 'form', product_license: @product_license %>

<%= link_to 'Show', @product_license %> |
<%= link_to 'Back', product_licenses_path %>

app/views/product_licenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Licenses</h1>

<table>
  <thead>
    <tr>
      <th>License Key</th>
      <th>Product Name</th>
      <th>Purchasing Client</th>
      <th>Client Seat</th>
      <th>Service Tag</th>
      <th>Purchased</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_licenses.each do |product_license| %>
      <tr>
        <td><%= product_license.license_key %></td>
        <td><%= product_license.product_name %></td>
        <td><%= product_license.purchasing_client %></td>
        <td><%= product_license.client_seat %></td>
        <td><%= product_license.service_tag %></td>
        <td><%= product_license.purchased? %></td>
        <td><%= link_to 'Show', product_license %></td>
        <td><%= link_to 'Edit', edit_product_license_path(product_license) %></td>
        <td><%= link_to 'Destroy', product_license, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product License', new_product_license_path %>

app/views/product_licenses/new.html.erb
<h1>New Product License</h1>

<%= render 'form', product_license: @product_license %>

<%= link_to 'Back', product_licenses_path %>

app/views/product_licenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>License key:</strong>
  <%= @product_license.license_key %>
</p>

<p>
  <strong>Product name:</strong>
  <%= @product_license.product_name %>
</p>

<p>
  <strong>Purchasing client:</strong>
  <%= @product_license.purchasing_client %>
</p>

<p>
  <strong>Client seat:</strong>
  <%= @product_license.client_seat %>
</p>

<p>
  <strong>Service Tag:</strong>
  <%= @product_license.service_tag %>
</p>

<%= link_to 'Edit', edit_product_license_path(@product_license) %> |
<%= link_to 'Back', product_licenses_path %>